### PR TITLE
Add graph for free home directory usage %

### PR DESCRIPTION
**Pull request by yuvipanda**
NFS disk filling up is one of the leading cause of outages. This PR adds:

- An example node_exporter deployment that exports metrics for filesystem usage, so we can add a...
- Chart in the JupyterHub dashboard, showing % of free space left.

This would be a decent place *later* to add a per-user usage stats metric collector *eventually*, not now though :)

Ref https://github.com/2i2c-org/infrastructure/pull/1992

### CODE REVIEW

**Review by GeorgianaElena — APPROVED** [review]
This looks good to me. Thanks @yuvipanda!

I have one idea around the location of this graph. Maybe it is worth creating a new dashboard for graphs that require additional setup for them to work to avoid having empty graphs?

**Review by minrk — APPROVED** [review]
Seems useful to have! I'm wondering about how configurable things should be here, but at a first level "what's useful to you" works for me at the moment.

**Review by consideRatio — COMMENTED** [review]
Nice, having something like this is great!!

I'm a bit opined about the naming that is now tightly coupled with the concept of home folders (`home` `homeSpace` `home-metrics`). In practice, this dashboard is monitoring metrics about the space available in a shared storage volume (mounted via a PVC) where home directories and sometimes also more things are located.

>### Home Directory Space Left
>
>In many common z2jh configurations, home directories are setup via a shared
filesystem (like NFS, AzureFile, etc).

In the hub.jupytearth.org deployment the shared volume used for home folders include other shared folders. I've also seen deployments where users get their individual disk for home folder storage but still mounts a shared storage volume which would be relevant to monitor. Due to that, I'm thinking about letting at least the technical references (k8s labels, volume references, dashboard variables) mention a "shared storage" or "shared volume" rather rather than "home".

@yuvipanda @GeorgianaElena @minrk what do you think about updating naming of variables etc from `home` to `shared-storage` or `shared-volume`?

**Comment by yuvipanda** [comment]
@GeorgianaElena I'd love to keep it in the same dashboard - IMO monitoring isn't complete if this (which is one of the largest source of outages) isn't present. And users *should* deploy something like this.

@consideRatio How *strongly* do you feel about this? I'd love to keep it as is, as 'shared storage' generally has more specific connotations around *who all have access to the storage*, and 'home directory' is a fairly well understood concept. However, I have limited cycles and time, so if you feel really strongly about it, I'd disagree but do it anyway because of just lack of time :) I am worried that instead this PR will just sort of 'hang here' forever if we get into a naming discussion, so my goal is to avoid a conversation about naming at all costs. So lmk if you feel strongly.

**Comment by yuvipanda** [comment]
To explain the confusion bit, often shared compute environments have a private space ('your home directory') and a *shared* space that is visible to everyone. In our case, we re-use the home directory volume for shared storage, but that's not always the case. Usually your 'shared space' filling up shouldn't cause server startups to fail, but your home directory filling up would.

"Do not participate in discussions about naming things" is perhaps going to be the hardest of my new years' things to keep haha.

**Comment by consideRatio** [comment]
This is awkward as I strongly value thoughtful naming, but don't want to push you into things you don't want to consider. Yet none of us should invest time in details that won't matter, but I do think this will matter - so I'm going for it.

To offload you from doing work I opened this PR to this PR branch https://github.com/yuvipanda/grafana-dashboards/pull/1.

**Comment by yuvipanda** [comment]
I clarified this with @consideRatio during a prior scheduled video call, but wanted to re-iterate :)

I completely agree that thoughtful naming is really important! I'm mostly just trying to recognize and understand my own problems with leaving things incomplete, and PRs left hanging open. So my goal is to just not have a personal opinion wherever possible, and unconditionally accept the other person's suggestion. No judgement at all!

So I deeply appreciate that you made the PR, @consideRatio. My goal is to recognize the limits of my own time, and reduce the amount of work I do. Your PR made that very easy! \o/

**Pull request merged**
