### PR TITLE
Replace global dashboard with activity dashboard

### LINKED ISSUE #78: Expose Global Users Dashboard as a timeseries
The current Global Users Dashboard uses a "bar gauge" plot for its data, which looks like this:

image

However, this removes any temporal information, which is particularly useful if you want to look at trends of users over time. This information is already stored within the query for the above plot, it's just not being displayed because:

1. Bar gauge just displays a single statistic, no time
2. The default amount of historical data is quite low

However, by lengthening the history of data and switching to a line plot, you get much more rich information:

image

### Propose

I'd like to by default ship a version of the Global Users Dashboard that contains, say, the last 3 months of data as a line plot, in addition to the bar gauge data.

### Implementation

I think the code that defines the bar gauge chart is below, so hopefully it wouldn't be too hard to modify it to be a line chart, and to include more historical data by default.

https://github.com/jupyterhub/grafana-dashboards/blob/03e10922019006f4200dec2730300baf558c15be/global-dashboards/global-usage-stats.jsonnet#L8-L18

### LINKED ISSUE #111: Stop generating global dashboard using state in specific grafana instance
This project's dashboards are jsonnet templates that render to grafana readable `.json` dashboard files.

One jsonnet dashboard template stands out though, the global dashboard. It needs to be generated using explicitly listed datasource names - names that are unique to the grafana instance. This is handled by the deploy.py script, which when asked to dpeloy the dashboards to a grafana instance first reads information about data sources, and then passes that to `jsonnet` when rendering the global dashboard.

I'd like us to transition away from generating the global dashboard using grafana instance specific state, because then:

1. We can pre-render all dashboards and publish them (#63)
2. Users of the global dashboard doesn't have to re-generate and re-deploy the dashboards if for example a datasource is added

The reason this was done in the first place is that it wasn't (and still isn't) possible to have a single panel providing info from a variable set of datasources.

<details><summary>About the impossibility of having a single panel querying X datasources</summary>

While its possible to repeat a panel or row of panels per datasource, it doesn't seem to be possible to repeat a query per datasource within a panel.

- https://www.reddit.com/r/grafana/comments/pprmfp/repeating_query_per_multivalue_variable/?rdt=41004
- https://community.grafana.com/t/dashboard-datasource-include-all-not-working-to-query-multiple-dbs/91103/9?u=consideratio
  > **But all/multiselect of datasource doesn’t fit into current Grafana implementation.** Each query has reference e. g. A, which then can be used in expression, transformation.
- https://community.grafana.com/t/repeat-queries-for-all-datasources/43490

</details>

I propose we accept this limitation, and pivot to provide multiple panels or rows of panels - one per datasource (one per prometheus-server / one per k8s cluster with hubs).

## Proposal

We provide the ability to view one row of these four panels per datasource:

dashboard-idea

These four panels are already available in the "Jupyterhub dashboard" within a row, so in practice I suggest a modification there to support repeating these four panels and deleting the global dashboard entirely rather than providing the same stuff in two places.

## What we currently have and the proposal replaces

image

### LINKED ISSUE #118: Global dashboard - Use JupyterHub's active users metric instead of counting pods
We have current / daily / weekly / monthly users in the JupyterHub Dashboard, under the "Hub usage" row:

image

They rely on JupyterHub's metric doing the counting of users.

In the global dashboard though we count pods instead I think, but that ought to be more complicated because you need to check for all pods popping up and going away etc.

### PR DESCRIPTION
**Pull request by consideRatio**
The activity.jsonnet dashboard is extracting four panels from the jupyterhub.jsonnet dashboard. The running servers panel and daily/weekly/monhtly active users panels.

By doing this, we get a dashboard with only those four panels, grouped into a row. This row is then made repeatable over the prometheus datasource variable. With a repeating row, we could end up with very many rows, making any panels below hard to get to. Due to that, it makes sense to use repeating rows in a dedicated dashboard.

The global dashboard that is being deleted made use of hardcoded state in the grafana instance it was being deployed to. This then also required regular re-deploys of the dashboard just to update the hardcoded entries.

Further, the global dashboard couldn't be pre-rendered and re-used across grafana instances - because it had grafance instance specific state within it.

With the new Activity dashboard, we can avoid all this complexity and possibly publish pre-rendered dashboards that any grafana instance can install directly.

- Fixes #111
- Fixes #118
- Fixes #78

### New dashboard (redacted)

Rows with four panels are repeating per datasource here.

activity-dashboard

### Old dashboard (redacted)

An individual panel is having hardcoded queries to all datasources as found when deploying the dashboard - which required the deploy.py script as it fetches info about all datasources.

global-dashboard

### CODE REVIEW

**Comment by choldgraf** [comment]
I really like the look of the new dashboard. If it makes things less brittle and more maintainable as well then I think it's worth merging once folks are happy with the implementation.

**Comment by consideRatio** [comment]
> I still think it would be really helpful to have aggregate graphs (eg by stacking graphs across clusters into a single plot), but perhaps that's not possible directly within grafana?

Not without hardcoding datasources =/ The "single plot" (aka. panel in grafana terminology) is the crux - grafana doesn't support functionality to let one panel reference a variable amount of datasources in its queries. One query per datasource, and a variable amounts of queries isn't possible.

**Comment by choldgraf** [comment]
Then it sounds like the solution would be to document how one could manually grab the data from this dashboard in order to do whatever you want with it. Does that sound right? And does that sound complicated?

**Review by choldgraf — APPROVED** [review]
I'm approving the PR to make it clear that I don't think my comments above should block this one, as I think it's definitely an improvement! I can't comment on the implementation however, so I'll let @consideRatio and/or others decide how to move forward.

**Comment by GeorgianaElena** [comment]
Thanks for raising this @consideRatio. As the person introducing the global dashboards experiment, creating it was motivated by @choldgraf's need to have all clusters available in a panel. So, if @choldgraf is ok with removing it and build similar usage graphs outside of Grafana then go for it 👍🏼 I don' think anyone else used this dashboard anyway, and this was part of the reason for keeping out separated then the general ones.

Also, extracting the running servers panel and daily/weekly/monhtly active users panels in an activity dashboard sounds more intuitively to find I think.

Also, implementation wise everything looked good to me.

**Comment by consideRatio** [comment]
Thank you for reviewing @choldgraf and @GeorgianaElena!

With OK from @choldgraf and @GeorgianaElena, I'll go for a merge here.

I'm marking #78 as fixed as well with this, but leave #79 open as an issue to represent wanting to have a single panel to present activity from all prometheus datasources (could be k8s clusters as it is for 2i2c) - something that is believed to not to be possible without hardcoding things currently in the dashboard definition (or generating it with state from specific grafana instances).

With my JupyterHub hat on, I think its a bit out of scope for this project to provide a dashboard that combines multiple prometheus datasources to present a super-panel if it means doing the workarounds required to do it as currently needed.

**Pull request merged**
