### PR TITLE
Allow filtering user pod diagnostics by node & add resource guarantee panels

### PR DESCRIPTION
**Pull request by yuvipanda**
- Per node filter is very helpful when diagnosing node falures
- Added panels for cpu and memory guarantees provided

Inspired by debugging https://github.com/2i2c-org/infrastructure/issues/2430

### CODE REVIEW

**Review by consideRatio — COMMENTED** [review]
I find this to be a very relevant feature, big :+1: for this kind of filtering support!

---

JupyterHub's terminology of "guarantee" maps to k8s terminolgoy of "requests". I'd like to stay with the k8s native terminology in this context, making us use the word "requests" instead, what do you think?

**Comment by yuvipanda** [comment]
@consideRatio done

**Review by minrk — APPROVED** [review]

**Comment by consideRatio** [comment]
@yuvipanda you forgot to push the commit I think

**Comment by yuvipanda** [comment]
@consideRatio fixed!

**Review by consideRatio — APPROVED** [review]

**Comment by consideRatio** [comment]
Nice!!!

Btw you can deploy to 2i2c by running the github workflow from the github web UI at 2i2c-org/infrastructure

/ from mobile

**Pull request merged**
